version: '3.9'

services:
    app:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile.dev
            args:
                DOCKER_BUILDKIT: 1
        restart: unless-stopped
        ports:
            - '3000:3000'
        volumes:
            - .:/app
        depends_on:
            - database

    database:
        container_name: postgres
        image: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - '${DATABASE_EXTERNAL_PORT}:5432'
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}

volumes:
    postgres-data:
