version: '3.9'

services:
    app:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile.dev
            args:
                DOCKER_BUILDKIT: 1
        restart: unless-stopped
        ports:
            - '3000:3000'
        volumes:
            - .:/app
        depends_on:
            - database

    database:
        container_name: mysql
        image: mysql:latest
        restart: unless-stopped
        command:
            [
                '--default-authentication-plugin=caching_sha2_password',
                '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',
            ]
        ports:
            - '${DATABASE_EXTERNAL_PORT}:3306'
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

volumes:
    db_data:
